// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/alexw1983/monkeycom-go-v2/models"

func Attributes(character models.Character) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row\"><div class=\"col-sm-6\"><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Strength", character, character.Strength, []models.Skill{models.Athletics}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Dexterity", character, character.Dexterity, []models.Skill{models.Acrobatics, models.SleightOfHand, models.Stealth}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Constitution", character, character.Constitution, []models.Skill{}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div><div class=\"col-sm-6\"><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Intelligence",
			character,
			character.Intelligence,
			[]models.Skill{models.Arcana, models.History, models.Investigation, models.Nature, models.Religion}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Wisdom",
			character,
			character.Wisdom,
			[]models.Skill{models.AnimalHandling, models.Insight, models.Medicine, models.Perception, models.Survival}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><div class=\"row mb-2\"><div class=\"col-sm-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AttributeBox("Charisma",
			character,
			character.Charisma,
			[]models.Skill{models.Deception, models.Intimidation, models.Performance, models.Persuasion}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// func RollSkillURL(c models.Character, s models.Skill) string {
// 	return "/dnd/character/" + c.UserId + "/roll/" + s.String()
// }

// templ SkillRow(c models.Character, s models.Skill) {
// 	<style>
// 	.skill-row {
// 		display: flex;

//			align-items: flex-end;
//		}
//		</style>
//		<div hx-get={ RollSkillURL(c, s) } class="skill-row">
//			{ s.String() }
//			[{ strconv.Itoa(c.GetAttributeBonus(s)) }]
//			<div>
//				<input
//					type="radio"
//					id="proficient"
//					onclick="return false;"
//					if c.IsProficient(s) {
//						checked
//					}
//				/>
//			</div>
//			<div>
//				<input
//					type="radio"
//					id="proficient"
//					onclick="return false;"
//					if c.HasExpertise(s) {
//						checked
//					}
//				/>
//			</div>
//			// <div>
//			// 	<input
//			// 		class="form-check-input"
//			// 		type="radio"
//			// 		name="inlineRadioOptions"
//			// 		id="expertise"
//			// 		value="expertise"
//			// 		onclick="return false;"
//			// 		if c.HasExpertise(s) {
//			// 			checked="checked"
//			// 		}
//			// 	/>
//			// 	// <label class="form-check-label" for="inlineRadio1">1</label>
//			// </div>
//		</div>
//		// <input
//		// 	class="form-check-input"
//		// 	type="checkbox"
//		// 	value=""
//		// 	onclick="return false;"
//		// 	id="checkDefault"
//		// 	if s.Proficient {
//		// 		checked="checked"
//		// 	}
//		// />
//		// <label class="form-check-label ms-2" for="checkDefault">
//		// 	{ label }
//		// </label>
//	}
var _ = templruntime.GeneratedTemplate
