// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DicePit() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n        .dice-pit {\n            border: 1px solid black;\n            border-radius: 8px;\n            padding: 1rem;\n            background-color: #f0f0f0;\n            margin-bottom: 1rem;\n            min-height: 500px;\n        }\n\n\t\t#DicePit {\n\t\t\tposition:relative;\n\t\t\tpadding: 1rem;\n\t\t\tmargin: 1rem;\n\t\t\twidth: 90%;\n\t\t\t\n\t\t\tbackground: #ddd;\n\t\t}\n\n\t\t.loader {\n\t\t\tposition: relative;\n\t\t\tborder: 16px solid #f3f3f3;\n\t\t\tborder-radius: 50%;\n\t\t\tborder-top: 16px solid #3498db;\n\t\t\twidth: 70px;\n\t\t\theight: 70px;\n\t\t\tleft:40%;\n\t\t\ttop:40%;\n\t\t\t-webkit-animation: spin 2s linear infinite; /* Safari */\n\t\t\tanimation: spin 2s linear infinite;\n\t\t}\n\t\t#DiceLoader{\n\t\t\topacity\n\t\t\tposition: absolute;\n\t\t\ttop:0px;\n\t\t\tleft:0px;\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tbackground: black;\n\t\t\topacity: .5;\n\t\t}\n\t\t.loader-container{\n\t\t\tposition:relative;\n\t\t\theight: 300px;\n\t\t\twidth: 200px;\n\t\t\tborder:1px solid\n\t\t}\n\n\t\t\t/* Safari */\n\t\t@-webkit-keyframes spin {\n\t\t\t0% { -webkit-transform: rotate(0deg); }\n\t\t\t100% { -webkit-transform: rotate(360deg); }\n\t\t}\n\n\t\t@keyframes spin {\n\t\t\t0% { transform: rotate(0deg); }\n\t\t\t100% { transform: rotate(360deg); }\n\t\t}\n\n    </style><div class=\"row\"><div class=\"col-sm-12\"><div class=\"dice-pit\"><div class=\"row\"><div class=\"col-8\"><h6>Dice Pit</h6><p>Roll your dice here!</p></div><div id=\"DicePit\" class=\"loader-container\"><div id=\"DiceLoader\"><div class=\"loader\"></div></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
