// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DicePit() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n        .dice-pit {\n            border: 1px solid black;\n            border-radius: 8px;\n            padding: 1rem;\n            background-color: #f0f0f0;\n            margin-bottom: 1rem;\n            min-height: 500px;\n        }\n\n\t\t#DicePit {\n\t\t\tpadding: 1rem;\n\t\t\tmargin: 1rem;\n\t\t\theight: 400px;\n\t\t\twidth: 90%;\n\t\t\toverflow-y: scroll;\n\t\t\tbackground: #ddd;\n\t\t}\n\n\n\t\t.loader {\n\t\t\twidth: 48px;\n\t\t\theight: 48px;\n\t\t\tborder-radius: 50%;\n\t\t\tposition: relative;\n\t\t\tanimation: rotate 1s linear infinite;\n\t\t\t\n\t\t}\n\t\t.loader::before , .loader::after {\n\t\t\tcontent: \"\";\n\t\t\tbox-sizing: border-box;\n\t\t\tposition: absolute;\n\t\t\tinset: 0px;\n\t\t\tborder-radius: 50%;\n\t\t\tborder: 5px solid #FFF;\n\t\t\tanimation: prixClipFix 2s linear infinite ;\n\t\t}\n\t\t.loader::after{\n\t\t\ttransform: rotate3d(90, 90, 0, 180deg );\n\t\t\tborder-color: #FF3D00;\n\t\t}\n\n\t\t@keyframes rotate {\n\t\t\t0%   {transform: rotate(0deg)}\n\t\t\t100%   {transform: rotate(360deg)}\n\t\t}\n\n\t\t@keyframes prixClipFix {\n\t\t\t0%   {clip-path:polygon(50% 50%,0 0,0 0,0 0,0 0,0 0)}\n\t\t\t50%  {clip-path:polygon(50% 50%,0 0,100% 0,100% 0,100% 0,100% 0)}\n\t\t\t75%, 100%  {clip-path:polygon(50% 50%,0 0,100% 0,100% 100%,100% 100%,100% 100%)}\n\t\t}\n    </style><div class=\"row\"><div class=\"col-sm-12\"><div class=\"dice-pit\"><div class=\"row\"><div class=\"col-8\"><h6>Dice Pit</h6><p>Roll your dice here!</p></div><div class=\"col-4\"><div id=\"DiceLoader\" class=\"loader htmx-indicator\"></div></div><div id=\"DicePit\"></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
